### ISSUE TITLE
Add screenshot?

### ISSUE THREAD

**Issue by jtdaugherty** [evanrelf/sudoku#2]
Hi, I'm the author of `brick`. I just found your project and thought it would be a great addition to the [Brick featured projects list](https://github.com/jtdaugherty/brick#featured-projects), but first I'm wondering if you'd be willing to take a screenshot and add it to your README. :) If not, no big deal.

**Comment by evanrelf** [comment]
Hi @jtdaugherty, thanks for making `brick`! It would be an honor to have my project on your list. I can add a screenshot.

I will warn you though: I was pretty new to Haskell when I wrote this, so it's not the best example of using `brick` or Haskell :-)

**Comment by jtdaugherty** [comment]
Awesome! As far as the code itself goes, that's not really the focus. I mean, yes, if someone wanted to understand how you did what you did, they could certainly look, but my intention with listing projects is to show what interesting things people have accomplished rather than to showcase a particular kind of Haskell code. The idea is to show what is possible, not what is expertly done.

**Comment by jtdaugherty** [comment]
Done: https://github.com/jtdaugherty/brick/commit/66d443bb2edcf6a1dba2192134abddc3b241d796

**Comment by jtdaugherty** [comment]
(Also mentioned here: https://twitter.com/brick_haskell/status/1074118232796098560)
